---

- name: Setup and run the LE audit
  block:
  - name: Setup the LE audit
    include_tasks: LE_audit_setup.yml
    when:
    - rhel7cis_setup_audit|bool
    tags:
    - setup_audit
    
  - name: retrieve audit content files from git
    git:
      repo: "{{ rhel7cis_audit_file_git }}"
      dest: "{{ rhel7cis_audit_dir }}"
      version: main
    when:
    - rhel7cis_audit_content == 'git'

  - name: copy to audit content files to server
    copy:
      src: "{{ rhel7cis_audit_local_copy}}"
      dest: "{{ rhel7cis_audit_dir }}"
    when:
    - rhel7cis_audit_content == 'copy'

  - name: get audit content from url
    get_url:
      url: "{{ rhel7_audit_files_url }}"
      dest: "{{ rhel7cis_audit_dir }}"
    when:
    - rhel7cis_audit_content == 'get_url'

- name: Check Goss is available
  block:
  - name: Check for goss file
    stat:
      path: "{{ goss_bin }}"
    register: goss_available
  
  - name: If audit ensure goss is available
    assert:
      msg: "Audit has been selected: unable to find goss binary at {{ goss_bin }}"
    when: 
    - not goss_available.stat.exists
  when:
  - rhel7cis_run_audit|bool

- name: "Check whether machine is UEFI-based"
  stat:
    path: /sys/firmware/efi
  register: rhel_07_efi_boot
  tags:
  - goss_template

- name: set fact for legacy or uefi boot
  set_fact:
    rhel7cis_legacy_boot: 'true'
  when: not rhel_07_efi_boot.stat.exists
  tags:
  - goss_template

- name: Copy ansible default vars values to test audit
  template:
    src: ansible_vars_goss.yml
    dest: "{{ goss_vars_path }}"
    mode: '0600'
  when:
  - rhel7cis_run_audit|bool
  tags:
  - goss_template
  
- name: "Run pre_remediation {{ benchmark }} audit"
  goss:
    goss_path: "{{ goss_bin }}"
    path: "{{ goss_file }}"
    vars_path: "{{ goss_vars_path }}"
    format: "{{ goss_format }}"
    output_file: "{{ pre_audit_outfile }}"
  failed_when: false

- name: "capture data  {{ pre_audit_outfile }}"
  command: "cat {{ pre_audit_outfile }}"
  register: pre_audit
  changed_when: false 
    
- name: Capture pre-audit result
  set_fact: 
    pre_audit_summary: "{{ pre_audit.stdout | from_json |json_query(summary) }}"
  vars:
    summary: 'summary."summary-line"'